language: python
python: 2.7
env:
  - PLONE_VERSION=5.0
  - PLONE_VERSION=5.1 QA=true
install:
  - sed -ie "s#travis-5.x.cfg#travis-$PLONE_VERSION.x.cfg#" travis.cfg
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg -N -q
script: bin/test
after_success:
  - test -v QA && bin/coverage.sh && pip install -q coveralls && coveralls || true
  - test -v QA && bin/code-analysis || true
after_failure:
  - bin/buildout annotate -c travis.cfg
